vim.o.swapfile = false
local root = vim.fn.tempname()
vim.fn.mkdir(root .. "/a/deep", "p")
vim.fn.mkdir(root .. "/b/other", "p")
root = vim.uv.fs_realpath(root)
local first, second = root .. "/a/deep/first.txt", root .. "/b/other/second.txt"
vim.fn.writefile({ "one" }, first)
vim.fn.writefile({ "two" }, second)
local workspace = require("workspace")
assert(workspace.add({ root .. "/a", root .. "/b" }))
local scanner = require("workspace.scan")
local real_list, scans = scanner.list, {}
scanner.list = function(roots, dirs, callback, depth)
  assert(depth == 1 and #roots == 1)
  scans[#scans + 1] = roots[1]
  return real_list(roots, dirs, callback, depth)
end
local function edit(path)
  vim.api.nvim_set_current_buf(vim.fn.bufadd(path))
end
edit(first)
local editor = vim.api.nvim_get_current_win()
local source = require("workspace.neotree")
source.toggle_tree()
local state = require("neo-tree.sources.manager").get_state("workspace")
local function selected(path)
  return vim.wait(3000, function()
    local current = state.tree and state.tree:get_node()
    return current and current:get_id() == path
  end)
end
assert(selected(first), "opening tree did not reveal current file")
assert(#scans == 2, "reveal should scan only ancestors")
vim.api.nvim_set_current_win(editor)
edit(second)
assert(selected(second), "buffer switch did not reveal file in another root")
assert(vim.api.nvim_get_current_win() == editor, "follow stole focus")
assert(#scans == 4)
edit(first)
assert(selected(first) and #scans == 4, "cached follow rescanned")
local outside = root .. "/outside.txt"
vim.fn.writefile({ "outside" }, outside)
edit(outside)
vim.wait(100, function() return false end)
assert(state.tree:get_node():get_id() == first and #scans == 4, "outside file changed tree")
source.toggle_tree()
edit(second)
vim.wait(100, function() return false end)
assert(not state.winid or not vim.api.nvim_win_is_valid(state.winid), "follow opened closed tree")
source.toggle_tree()
assert(selected(second))
vim.api.nvim_set_current_win(editor)
vim.cmd.source(vim.env.MYVIMRC)
source = require("workspace.neotree")
source.toggle_tree() -- close after reload
source.toggle_tree()
state = require("neo-tree.sources.manager").get_state("workspace")
vim.api.nvim_set_current_win(editor)
edit(first)
assert(selected(first), "follow broken after reload")
assert(#vim.api.nvim_get_autocmds({ group = "WorkspaceTree", event = "BufEnter" }) == 1)
-- Deep package paths must reveal the filename, not just a wall of indentation.
local deep = root .. "/b/other/" .. string.rep("level/", 18)
vim.fn.mkdir(deep, "p")
local deep_file = deep .. "DeepFile.java"
vim.fn.writefile({ "deep" }, deep_file)
source.commands.refresh(state)
edit(deep_file)
assert(selected(deep_file), "deep file was not revealed")
vim.api.nvim_win_call(state.winid, function()
  local view = vim.fn.winsaveview()
  local line = vim.api.nvim_get_current_line()
  local start = assert(line:find("DeepFile.java", 1, true), vim.inspect({ line = line, view = view }))
  local column = vim.fn.strdisplaywidth(line:sub(1, start - 1))
  assert(view.leftcol > 0, "deep follow left the filename off-screen")
  assert(column - view.leftcol >= 0 and column - view.leftcol + #"DeepFile.java"
    <= vim.api.nvim_win_get_width(0), "filename is not inside tree viewport")
end)
assert(vim.api.nvim_get_current_win() == editor, "horizontal reveal stole focus")
-- A delayed ancestor load must follow the newer file, never the old target.
vim.fn.mkdir(root .. "/a/new", "p")
local late = root .. "/a/new/late.txt"
vim.fn.writefile({ "late" }, late)
local pending
require("workspace.scan").list = function(_, _, callback) pending = callback end
source.commands.refresh(state)
edit(late)
assert(vim.wait(1000, function() return pending ~= nil end))
edit(outside)
vim.wait(100, function() return false end)
local cursor = state.tree:get_node():get_id()
pending({ { path = root .. "/a/new", relative = "new", type = "directory" } })
assert(state.tree:get_node():get_id() == cursor, "late result moved cursor to stale file")
source.toggle_tree()
pending({})
assert(not state.winid or not vim.api.nvim_win_is_valid(state.winid), "late follow reopened tree")
print("workspace follow tests passed")
vim.cmd("qa!")
