local root = vim.fn.tempname()
vim.fn.mkdir(root, "p")
root = vim.uv.fs_realpath(root)
local function git(args)
  local result = vim.system(vim.list_extend({ "git", "-C", root }, args), { text = true }):wait()
  assert(result.code == 0, result.stderr)
end
git({ "init", "-q" })
git({ "-c", "user.name=Test", "-c", "user.email=test@example.invalid", "commit", "--allow-empty", "-qm", "fixture" })
local linked = root .. "-linked"
git({ "worktree", "add", "-qb", "linked", linked })
local function edit(path)
  vim.cmd.enew()
  vim.api.nvim_buf_set_name(0, path)
  vim.api.nvim_exec_autocmds("BufEnter", { buffer = 0 })
end
local status = require("config.worktree_status")
edit(linked .. "/file.txt")
assert(vim.wait(2000, function() return status.component() == vim.fs.basename(linked) end))
edit(root .. "/file.txt")
assert(status.component() == "", "main checkout retained linked label")
vim.wait(100, function() return false end)
assert(status.component() == "")
edit(linked .. "/another.txt")
assert(status.component() == vim.fs.basename(linked), "cached linked label missing")
vim.cmd.source(vim.env.MYVIMRC)
status = require("config.worktree_status")
assert(vim.wait(2000, function() return status.component() == vim.fs.basename(linked) end))
local config = require("lualine").get_config()
assert(#config.sections.lualine_c == 0 and #config.inactive_sections.lualine_c == 0)
assert(#config.winbar.lualine_c > 0, "winbar filepath removed")
assert(#vim.api.nvim_get_autocmds({ group = "WorktreeStatus" }) == 2)
print("worktree status tests passed")
vim.cmd("qa!")
